name: env_solverLearning_gpu
channels:
  - pytorch
  - anaconda
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - anyio=4.0.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.2.3
  - asttokens=2.4.0
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.2
  - blas=2.118
  - blas-devel=3.9.0
  - bleach=6.0.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - casadi=3.6.3
  - certifi=2024.2.2
  - cffi=1.15.1
  - charset-normalizer=3.2.0
  - colorama=0.4.6
  - comm=0.1.4
  - contourpy=1.1.1
  - cuda-cccl=12.2.128
  - cuda-cccl_win-64=12.1.109
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cudart-dev_win-64=12.1.105
  - cuda-cudart-static=12.1.105
  - cuda-cudart-static_win-64=12.1.105
  - cuda-cudart_win-64=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.1.105
  - cuda-opencl-dev=12.1.105
  - cuda-profiler-api=12.2.128
  - cuda-runtime=12.1.0
  - cuda-version=12.1
  - cupy=13.0.0
  - cupy-core=13.0.0
  - cvxpy=1.3.2
  - cvxpy-base=1.3.2
  - cycler=0.11.0
  - debugpy=1.8.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - ecos=2.0.11
  - eigen=3.4.0
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - fastrlock=0.8.2
  - filelock=3.12.4
  - flit-core=3.9.0
  - fonttools=4.42.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - gettext=0.21.1
  - glib=2.78.0
  - glib-tools=2.78.0
  - gst-plugins-base=1.22.6
  - gstreamer=1.22.6
  - icu=73.2
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.1.0
  - intel-openmp=2023.2.0
  - ipopt=3.14.12
  - ipykernel=6.25.2
  - ipython=8.15.0
  - ipywidgets=8.1.1
  - isoduration=20.11.0
  - jedi=0.19.0
  - jinja2=3.1.2
  - joblib=1.3.2
  - json5=0.9.14
  - jsonpointer=2.4
  - jsonschema=4.19.1
  - jsonschema-specifications=2023.7.1
  - jsonschema-with-format-nongpl=4.19.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.3.1
  - jupyter_core=5.3.1
  - jupyter_events=0.7.0
  - jupyter_server=2.7.3
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.6
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.25.0
  - jupyterlab_widgets=3.0.9
  - khronos-opencl-icd-loader=2023.04.17
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.15
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcurand=10.3.3.129
  - libcurand-dev=10.3.3.129
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libdeflate=1.19
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflang=5.0.0
  - libglib=2.78.0
  - libhwloc=2.9.3
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.1.14
  - libogg=1.3.4
  - libosqp=0.6.3
  - libpng=1.6.39
  - libqdldl=0.1.5
  - libsodium=1.0.18
  - libsqlite=3.43.0
  - libtiff=4.6.0
  - libuv=1.44.2
  - libvorbis=1.3.7
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.11.5
  - libzlib=1.2.13
  - llvm-meta=5.0.0
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.1.3
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - metis=5.1.0
  - mistune=3.0.1
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - mumps-seq=5.2.1
  - munkres=1.1.4
  - nb_conda_kernels=2.3.1
  - nbclient=0.8.0
  - nbconvert-core=7.8.0
  - nbformat=5.9.2
  - nest-asyncio=1.5.6
  - networkx=3.1
  - notebook=7.0.4
  - notebook-shim=0.2.3
  - numpy=1.26.0
  - openjpeg=2.5.0
  - openmp=5.0.0
  - openpyxl=3.0.10
  - openssl=3.2.1
  - osqp=0.6.3
  - overrides=7.4.0
  - packaging=23.1
  - pandas=2.1.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.40
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - ply=3.11
  - pooch=1.7.0
  - prometheus_client=0.17.1
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - proxsuite=0.3.7
  - psutil=5.9.5
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.16.1
  - pyparsing=3.1.1
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.18.0
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytorch=2.2.0
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2023.3.post1
  - pywin32=306
  - pywinpty=2.0.11
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - qdldl-python=0.1.5.post2
  - qt-main=5.15.8
  - referencing=0.30.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.3
  - scikit-learn=1.3.1
  - scipy=1.11.2
  - scs=3.2.3
  - send2trash=1.8.2
  - simde=0.7.6
  - sip=6.7.11
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - stack_data=0.6.2
  - sympy=1.12
  - tbb=2021.10.0
  - terminado=0.17.0
  - threadpoolctl=3.2.0
  - tinycss2=1.2.1
  - tinyxml2=9.0.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - torchvision=0.15.2
  - tornado=6.3.3
  - traitlets=5.10.1
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - typing_utils=0.1.0
  - tzdata=2023c
  - ucrt=10.0.22621.0
  - uri-template=1.3.0
  - urllib3=2.0.5
  - vc=14.3
  - vc14_runtime=14.36.32532
  - vs2015_runtime=14.36.32532
  - wcwidth=0.2.6
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.6.3
  - wheel=0.41.2
  - widgetsnbextension=4.0.9
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.17.0
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - grpcio==1.62.1
      - markdown==3.6
      - pip==24.0
      - protobuf==5.26.1
      - setuptools==69.1.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - torchaudio==2.2.0
      - torchdiffeq==0.2.3
      - werkzeug==3.0.2
